#!/usr/bin/env python3
import json
import sqlite3
import argparse
import os
from pathlib import Path

def main():
    parser = argparse.ArgumentParser(description="Generate portable M3U playlists preserving the folder tree.")
    parser.add_argument("--outdir", help="Subdirectory inside 128mp3 for playlists (default: root of 128mp3)")
    args = parser.parse_args()

    config = {}
    if Path("config.json").exists():
        with open("config.json", 'r') as f:
            config = json.load(f)

    mp3_dir = Path(config.get("output_dir", "128mp3")).expanduser()
    playlist_dir = mp3_dir / args.outdir if args.outdir else mp3_dir
    playlist_dir.mkdir(parents=True, exist_ok=True)

    db_path = Path(config.get("db_path", "audio_database.db"))
    if not db_path.is_absolute():
        db_path = Path.cwd() / db_path

    conn = sqlite3.connect(str(db_path))
    conn.row_factory = sqlite3.Row
    cursor = conn.cursor()

    cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
    table_name = [t[0] for t in cursor.fetchall() if not t[0].startswith("sqlite_")][0]

    cursor.execute(f"PRAGMA table_info({table_name});")
    columns = [col['name'] for col in cursor.fetchall()]
    
    # Auto-detect the path column name across schema versions
    path_col = next((c for c in columns if c in ['file_path', 'path', 'filename', 'filepath', 'processed_path']), None)

    cursor.execute(f"SELECT {path_col}, title, artist, audio_vibe FROM {table_name} WHERE audio_vibe IS NOT NULL")
    rows = cursor.fetchall()

    playlists = {}
    for row in rows:
        vibe = row['audio_vibe']
        safe_name = "".join(c if c.isalnum() else "_" for c in vibe).strip("_").lower()
        while "__" in safe_name: 
            safe_name = safe_name.replace("__", "_")

        if safe_name not in playlists:
            playlists[safe_name] = []
        playlists[safe_name].append(row)

    print(f"🎵 Generating {len(playlists)} tree-preserved M3U playlists in '{playlist_dir}'...")
    
    for vibe_name, tracks in playlists.items():
        playlist_path = playlist_dir / f"{vibe_name}.m3u"
        with open(playlist_path, 'w', encoding='utf-8') as f:
            f.write("#EXTM3U\n")
            f.write("# REMARK: Playlist generated by audio_vibe acoustic analysis.\n")
            f.write("# REMARK: Paths preserve the album subfolder tree under 128mp3.\n")
            
            for track in tracks:
                title = track['title'] or "Unknown Title"
                artist = track['artist'] or "Unknown Artist"
                raw_path = track[path_col]
                
                if not raw_path:
                    continue
                
                p = Path(raw_path)
                parts = p.parts
                
                # Use your script's tuple slicing logic to preserve subfolders after 128mp3/musicraw
                rel_path = None
                for marker in ['128mp3', 'musicraw']:
                    if marker in parts:
                        idx = parts.index(marker)
                        rel_path = Path(*parts[idx+1:])
                        break
                
                if not rel_path:
                    # Fallback to last two components (Album/filename) if marker isn't matched
                    if len(parts) >= 2:
                        rel_path = Path(parts[-2]) / parts[-1]
                    else:
                        rel_path = Path(p.name)
                
                # Ensure correct .mp3 file extension
                rel_path = rel_path.with_suffix('.mp3')

                f.write(f"#EXTINF:-1,{artist} - {title}\n")
                f.write(f"{str(rel_path).replace(os.sep, '/')}\n")
        
        print(f"  ├── {vibe_name}.m3u ({len(tracks)} tracks)")

    conn.close()

if __name__ == "__main__":
    main()
